name: LinkCheck

# Run the check during a PR, hiding it under the high-latency Azure Pipelines runs.
on:
  pull_request:
    branches: [ master ]

env:
  URL: https://github.com/Microsoft/QuantumKatas/

jobs:
  KataBrokenLinkCheck:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Check out the repo under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    - name: Link Snitch
      uses: victoriadrake/link-snitch@v1.0.0

